<a href="https://colab.research.google.com/github/jeong1suk/DeepLearning/blob/math/%EB%94%A5%EB%9F%AC%EB%8B%9D%20%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%9D%98%20%EC%97%B0%EC%82%B0/04_Loss_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4-1: Datasets

## Code.4-1-1-: Dataset for Regression

In [1]:
import tensorflow as tf

In [11]:
N, n_feature = 8, 5
t_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
t_bias = tf.constant([10], dtype=tf.float32)

print(t_weights)
print(t_bias)

X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))

print(X.shape, t_weights.shape, t_bias.shape)

Y = tf.reduce_sum(t_weights * X, axis=1)  + t_bias
print("X(shape/dtype/data): {} / {}\n{}".format(X.shape, X.dtype, X.numpy()))
print("Y(shape/dtype/data): {} / {}\n{}".format(Y.shape, Y.dtype, Y.numpy()))

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([10.], shape=(1,), dtype=float32)
(8, 5) (5,) (1,)
X(shape/dtype/data): (8, 5) / <dtype: 'float32'>
[[-1.3654873  -2.7664077  -0.10707333  1.251496   -1.4663501 ]
 [ 1.2012979   2.0989676  -1.4181365  -0.42358673  0.5855257 ]
 [ 0.6203425   1.8839082   1.4766467   0.07159737 -0.06615648]
 [ 0.8836731  -0.18345691  0.6712433   1.1393728   0.01310209]
 [-0.05222293  0.8246089  -0.13729484 -1.4108541   1.2882141 ]
 [-0.7859492  -2.4499767   1.387347    0.59659684 -0.2983556 ]
 [ 1.0074149   0.21845025  1.0463079   0.21500759  1.001264  ]
 [-0.37048265 -1.0944635   0.67037976 -0.73305315 -1.6321698 ]]
Y(shape/dtype/data): (8,) / <dtype: 'float32'>
[ 0.45471   12.378105  18.773706  17.153492  11.982764   9.370748
 20.449589  -1.6413326]


## Code.4-1-2: Dataset for Binary Classification

In [ ]:
import tensorflow as tf

In [20]:
N, n_feature = 8, 5
t_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
t_bias = tf.constant([10], dtype=tf.float32)

X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
Y = tf.reduce_sum(t_weights * X, axis=1)  + t_bias
print(Y)
Y = Y > 5
print(Y)
Y = tf.cast(Y, tf.int32)
print(Y)
print("=" * 60)
print("X(shape/dtype/data): {} / {}\n{}".format(X.shape, X.dtype, X.numpy()))
print("Y(shape/dtype/data): {} / {}\n{}".format(Y.shape, Y.dtype, Y.numpy()))

tf.Tensor(
[15.412625   9.10476   13.071841   0.5981102  9.188585  11.609664
 16.828629  10.356081 ], shape=(8,), dtype=float32)
tf.Tensor([ True  True  True False  True  True  True  True], shape=(8,), dtype=bool)
tf.Tensor([1 1 1 0 1 1 1 1], shape=(8,), dtype=int32)
X(shape/dtype/data): (8, 5) / <dtype: 'float32'>
[[-0.17524023  0.85945296 -1.3599676  -0.28904188  1.8210061 ]
 [-0.6682548  -0.42388666  0.3284389   0.34603316 -0.3497322 ]
 [ 0.2748071  -0.74806243  0.3061695  -0.7944874   1.3105199 ]
 [-0.5782906  -1.0370731  -0.4799239  -0.58213943 -0.5962248 ]
 [-0.46889886  1.4817132  -0.5835278  -0.6014914   0.17012142]
 [-0.60697556  1.8718908   1.6479232  -1.7726274   0.12391952]
 [ 0.06310067  0.24444723  0.8870959   1.276237   -0.29792064]
 [-0.6603474   0.3809829   0.72173196 -1.1102608   0.5060619 ]]
Y(shape/dtype/data): (8,) / <dtype: 'int32'>
[1 1 1 0 1 1 1 1]


## Code.4-1-3: Dataset for Multi-class Classification

## Code.4-1-4: Dataset Objects